Move foreign key for inventory ids
chaosinventory/chaosinventory pull request #24
Opened 2021-02-09 11:49 UTC by clerie

Fixes #21

2021-02-09 11:52 UTC, clerie commented
I recomment waiting for #20 to get mergend before generating migrations.

2021-02-09 11:55 UTC, clerie commented
Also we should discuss, how we want to handle the migrations. Django want us to define a default for the new required `ForeignKey`, which is not an optimal. I would prefer deleting all existing entries.

2021-02-27 15:53 UTC, e1mo approved these changes
Looks good to me

2021-02-27 15:54 UTC, em0lar approved these changes

2021-02-27 18:53 UTC, e1mo requested changes
Oh wait, I just saw that the migration from #20 was deleted and the blank options are not represented in the models.

See https://github.com/chaosinventory/chaosinventory/compare/clerie%2Finventory-ids...clerie%2Fmodel-blanks?diff=unified

Or was I just looking wrong?

2021-02-28 12:35 UTC, clerie commented
> Oh wait, I just saw that the migration from #20 was deleted and the blank options are not represented in the models.

Ok, did a rebase and redone the migrations stuff. Hope its now ok.

2021-02-28 13:51 UTC, margau commented
It seems that we have the lint failing. Interestingly, that happens in a line that was not touched?

2021-02-28 18:50 UTC, e1mo requested changes
Looks good so far, thanks! However, I would be happier if the CI would be happy (:

See here for the full CI log: <https://github.com/chaosinventory/chaosinventory/pull/24/checks?check_run_id=1998086234>

2021-02-28 18:50 UTC, e1mo commented on src/chaosinventory/base/models.py
> +    )
```suggestion
    )
    
```

2021-02-28 18:50 UTC, e1mo commented on src/chaosinventory/base/models.py
> +    )
```suggestion
    )
    
```

2021-03-04 22:30 UTC, margau approved these changes

2021-03-05 06:55 UTC, e1mo approved these changes

2021-03-05 10:49 UTC, adnidor approved these changes

2021-03-05 10:49 UTC, merged