Create initials models.py based on ERD
chaosinventory/chaosinventory pull request #6
Opened 2021-01-17 20:00 UTC by e1mo

There are a few TODOs left, or things where I'd like to discuss the naming. I'll try to add those as comments to the files tomorrow.

2021-01-22 16:09 UTC, e1mo commented on src/chaosinventory/base/models.py
> +class InventoryIdSchema(CommonModel):
How do we identify different InventoryIdSchemas?

I would propose another field `name`, referring to a plugins module name and possibly sub-classes.

E.g. `chaosinventory.base.schemes.counting`, `chaosinventory.base.schemes.letters`, ...

2021-01-22 16:18 UTC, e1mo commented on src/chaosinventory/base/models.py
> +class InventoryIdSchema(CommonModel):
Okay my bad, it inherits `name` and `note` from CommonModel...

2021-01-22 19:16 UTC, clerie commented on src/chaosinventory/base/models.py
> +    in_item = models.ForeignKey(
Maybe `should_be_in_item`

2021-01-22 19:17 UTC, clerie commented on src/chaosinventory/base/models.py
> +    current_item = models.ForeignKey(
Maybe `is_currently_in_item`

2021-01-22 19:21 UTC, clerie commented on src/chaosinventory/base/models.py
> +    inventory_id = models.ForeignKey(
Items should get more than one inventory id

2021-01-22 19:26 UTC, clerie commented on src/chaosinventory/base/models.py
> +    in_item = models.ForeignKey(
`s/in_item/target_item/`

2021-01-22 19:26 UTC, clerie commented on src/chaosinventory/base/models.py
> +    location = models.ForeignKey(
`s/location/target_location/`

2021-01-29 12:08 UTC, clerie requested changes
There are some minor errors, but overall it looks good.

2021-01-29 12:08 UTC, clerie commented on src/chaosinventory/base/models.py
> +    inventory_ids = models.ManyToManyField(
This field should be a `ForeignKey` too.

2021-01-29 12:08 UTC, clerie commented on src/chaosinventory/base/models.py
> +    target_location = models.ForeignKey(
`target_location` should get a `related_name` definition too.

2021-01-29 12:08 UTC, clerie commented on src/chaosinventory/base/models.py
> +    name = models.CharField(max_length=255)
Line break is not consistent.

2021-01-29 12:08 UTC, clerie commented on src/chaosinventory/base/models.py
> +    name = models.CharField(max_length=255)
Put `max_length` in a new line.

2021-01-31 19:40 UTC, e1mo commented on src/chaosinventory/base/models.py
> +class Tag(models.Model):
_Discussed in our last conference, Tag does not require a note_

2021-02-03 16:48 UTC, clerie approved these changes

2021-02-03 16:51 UTC, adnidor approved these changes

2021-02-03 17:02 UTC, em0lar approved these changes

2021-02-03 17:26 UTC, merged